### ISSUE TITLE
cannot install on macosx

### ISSUE THREAD

**Issue by rexroof** [Aisbergg/python-docker-compose-templer#1]
```
$ pip install docker-compose-templer
Collecting docker-compose-templer
  Downloading https://files.pythonhosted.org/packages/13/7d/676f49321ad4eefa8883f001998491fb4d63cf981f3775715b1404299766/Docker_Compose_Templer-1.0.2-py3-none-any.whl
Collecting pyinotify (from docker-compose-templer)
  Downloading https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 3.1MB/s
    Complete output from command python setup.py egg_info:
    inotify is not available on macosx-10.14-x86_64

```

could inotify be optional?

**Comment by rexroof** [comment]
https://github.com/gorakhargosh/watchdog   appears to support this functionality, cross-platform

**Comment by aisbergg** [comment]
Hi, I refactored the code and made the auto render functionality optional so that `pyinotify` is now optional. Try the new [release](https://github.com/Aisbergg/python-docker-compose-templer/tree/v1.1.0) and see if it works for you.

I will look more into `watchdog`. It is more designed to watch for whole directories rather than single files, but I think there is a way to use it.

**Comment by rexroof** [comment]
Excellent! Thanks!
